### ISSUE TITLE
[Win7] Truecraft.Client has stopped working   .NET runtime error

### ISSUE THREAD

**Issue by RowenPM** [SirCmpwn/TrueCraft#240]
Launching the launcher works fine, I can generate a map, login, etc.

When I try to run a map or launch the client directly, it says "Truecraft.Client has stopped working"

When I check windows crash reports, there are 2 reports.

.NET runtime error:

```
Application: TrueCraft.Client.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at TrueCraft.Client.Rendering.TextureMapper.LoadDefaults(Microsoft.Xna.Framework.Graphics.GraphicsDevice)
   at TrueCraft.Client.TrueCraftGame.LoadContent()
   at Microsoft.Xna.Framework.Game.Initialize()
   at TrueCraft.Client.TrueCraftGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(Microsoft.Xna.Framework.GameRunBehavior)
   at TrueCraft.Client.Program.Main(System.String[])
```

Application error:

```
Faulting application name: TrueCraft.Client.exe, version: 1.0.5921.999, time stamp: 0x00000000
Faulting module name: KERNELBASE.dll, version: 6.1.7601.19135, time stamp: 0x56a1c680
Exception code: 0xe0434352
Fault offset: 0x000080d7
Faulting process id: 0xb4c
Faulting application start time: 0x01d1905f8a971229
Faulting application path: C:\Users\Rowen\Documents\Truecraft\TrueCraft.Client.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: d372b9f1-fc52-11e5-a280-4061865d2ba2
```

**Comment by SirCmpwn** [comment]
Need Windows user to work on this, I can't reproduce. Something related to the installation of the textures? I'm not sure.

**Comment by manio143** [comment]
The only folder present in the client directory is Content. If it's missing the exception above is thrown. Possibly the same for its subfolders.
